### PR TITLE
Fix for #12: Check Load return and if ALL Load fail, consider the loa…

### PR DESCRIPTION
**Pull request by pijalu**
…d as invalid

Signed-off-by: Pierre Poissinger <Pierre.Poissinger@ordina.be>

### CODE REVIEW

**Comment by asim** [comment]
Should we perhaps be returning an error at the end if any source fails to load?

**Comment by pijalu** [comment]
I was wondering for a long time about that... due to the ability of chaining/defaulting sources that 'may' lead to situation where it would always return one error (for one or more source)
eg: file only in dev, etcd in QA, consul in PRD...

Now I guess this could be 'fixed' by creating a dedicated type of error with more details tho... but is that considered an api 'change'. 

Any opinions as I am not really happy with sweeping errors under the rug either...

**Comment by asim** [comment]
Yea completely understand. I think the issue is if you're expecting an error on load and that only occurs if all sources load then there's a hidden edge case where you may never know of a failing source.

We should probably return an error at the end on any source loading issues. Defining error types gets a bit tricky because once we define them they need to stick around forever. Let's start by just returning an error and then we can look at defining types later.

Maybe something like
```
var gerrors []string

for _, source := range sources {
    set, err := source.Read()
    if err != nil {
        gerrors = append(gerrors, fmt.Sprintf("error loading source %s: %v", source.String(), err))
        continue
    }
}

if len(errors) > 0 {
  return errors.New(strings.Join(errors, "\n"))
}

return nil
```

**Comment by pijalu** [comment]
LGTM - will update the PR in a bit

**Comment by asim** [comment]
LGTM. Thanks.

**Pull request merged**
